
package javaproject;

/**
 *
 * @author Mihael
 */
/*
This is an example of a frame for the login window.
It doesn't have the "main" function. The "Main" class takes care of displaying and 
destruction.
Variable "done" is used for signaling to Main when to transition to the next frame.
Setting "done" to "true" will cause the frame's distruction and the end user will
be prompted with the appropriate workspace window (worker or admin) depending on the
"Main.id" variable.
A full implementation is needed for this class. See documentation. 
*/
public class loginFrame extends javax.swing.JFrame {

    public boolean done;
    
    /**
     * Creates new form loginFrame
     */
    public loginFrame() {
        done = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginA = new javax.swing.JButton();
        loginW = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginA.setText("admin login");
        loginA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAActionPerformed(evt);
            }
        });

        loginW.setText("worker login");
        loginW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginA)
                    .addComponent(loginW))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(loginA)
                .addGap(28, 28, 28)
                .addComponent(loginW)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void loginAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAActionPerformed
        // TODO add your handling code here:
        Main.id = "admin";
        done = true;
    }//GEN-LAST:event_loginAActionPerformed

    private void loginWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginWActionPerformed
        // TODO add your handling code here:
        Main.id = "worker";
        done = true;
    }//GEN-LAST:event_loginWActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginA;
    private javax.swing.JButton loginW;
    // End of variables declaration//GEN-END:variables
}
